# build with:
# sudo docker build -f Dockerfile.dev -t esmero/php-8.0.24-fpm:1.0.0-dev-multiarch . --no-cache
# from https://www.drupal.org/docs/8/system-requirements/drupal-8-php-requirements

FROM esmero/php-8.0.24-fpm:1.1.0-multiarch

# install the extensions we need for xdebug install
RUN set -eux; \
	apk add --no-cache --virtual .build-deps \
		autoconf \
        g++ \
        make \
	; \
	pecl install xdebug-3.0.4; \
    apk del --no-cache .build-deps

RUN { \
		echo 'zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20200930/xdebug.so'; \
		echo 'xdebug.remote_handler=dbgp'; \
		echo 'xdebug.client_port=9003'; \
		echo 'xdebug.start_with_request=yes'; \
		echo 'xdebug.connect_timeout_ms=500'; \
		echo 'xdebug.mode=develop,debug'; \
		echo 'xdebug.idekey=archipelago'; \
		echo "xdebug.client_host=host.docker.internal"; \
		echo "xdebug.log=/tmp/xdebug.log"; \ 
	} > /usr/local/etc/php/conf.d/10-xdebug.ini
